### ISSUE TITLE
vue-cli中preset自定义选择多模版问题

### ISSUE THREAD

**Issue by HidingDark** [cloud-templates/vue-preset#17]
想请教一下，目前这种方式仅适配了单模版的情况，如果想要在预设中让使用者自行选择模版的话，应该如何去做呢？总不能将多个模版都放在这一个仓库里面然后通过generator进行选择性render吧？

**Comment by cklwblove** [comment]
可以参考官方的 https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-service
