### ISSUE TITLE
在window环境下，eslint会报错Expected linebreak to be unix (linebreaks)

### ISSUE THREAD

**Issue by lawrence998** [cloud-templates/vue-preset#31]
在window环境下，eslint在终端会一直报错Expected linebreak to be unix (linebreaks)(window系统的换行跟liux系统的换行格式不一致)，因为@winner-fed/vue-cli-plugin-eslint这个控件依赖@winner-fed/eslint-config-win插件的eslint配置，在@winner-fed/vue-cli-plugin-eslint插件中的eslintOptions文件中的rules新增'linebreak-style': 'off'，也不生效，而且在.eslintrc文件下设置rules:{'linebreak-style': 'off'}无效

**Comment by cklwblove** [comment]
格式问题已解决
